version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    env_file: .env
    depends_on: [db, redis]
    ports:
      - "8000:8000"
  worker:
    build: ./worker
    env_file: .env
    depends_on: [backend, db, redis]
  playwright-bot:
    build: ./playwright-bot
    env_file: .env
    depends_on: [backend]
  frontend:
    build: ./frontend
    env_file: .env
    depends_on: [backend]
    ports:
      - "3000:3000"
